### ISSUE TITLE
Error in Output for Multiple Hypotheses with Different Variables

### ISSUE THREAD

**Issue by meli365** [tea-lang-org/tea-lang#43] opened 2020-04-22 18:07 UTC
When multiple `tea.hypothesize` calls are listed together, there seems to be a carry-over of variable names from one hypothesis output to the next.

For example, this [small drug example](https://github.com/emjun/tea-lang/blob/testing_and_documentation/examples/Drugs/drug_small_tea.py). With the first hypothesis uncommented, the second hypothesis still prints the correct **test results**, but it prints the **test assumptions** listing the variables from the first hypothesis (`drug` & `wedsBDI` instead of `sundayBDI` & `BDIchange`).

The results look something like this:
```
Test: kendalltau_corr
***Test assumptions:
Exactly two variables involved in analysis: drug, wedsBDI
Continuous OR ORDINAL (not nominal) data: drug
Continuous OR ORDINAL (not nominal) data: wedsBDI

***Test results:
name = Kendall's Tau Correlation
test_statistic = -0.07161
p_value = 0.84549
adjusted_p_value = 0.84549
alpha = 0.01
Null hypothesis = There is no relationship between sundayBDI and BDIchange.
Interpretation = Fail to reject the null hypothesis at alpha = 0.01. There is no relationship between sundayBDI and BDIchange.
```

Swapping the order of the hypotheses leads to similar behavior, with `sundayBDI` & `BDIchange` listed in the test assumptions instead of `drug` & `wedsBDI` for the last hypothesis:
```
Test: pointbiserial_corr_a
***Test assumptions:
Exactly two variables involved in analysis: sundayBDI, BDIchange
Continuous (not categorical) data: BDIchange
Normal distribution: BDIchange: NormalTest(W=0.9239336252212524, p_value=0.5341329574584961)
Variable is categorical: sundayBDI
Variable has two categories: sundayBDI
Equal variance: sundayBDI, BDIchange

***Test results:
name = Pointbiserial Correlation
test_statistic = 0.53028
p_value = 0.64417
adjusted_p_value = 0.64417
alpha = 0.01
Null hypothesis = There is no association between Ecstasy and Alcohol.
Interpretation = Fail to reject the null hypothesis at alpha = 0.01. There is no association between Ecstasy and Alcohol.
```

(The output is correct for whichever hypothesis runs first.)

**Comment by MaLiN2223** [comment] 2020-04-22 18:21
Possible duplicate of #8, I would close the previous one and keep this open as it provides an example.
The possible reason is that we utilize global variables, I tried to address this multiple times but it requires a major refactoring so I abandoned the idea for now.

**Comment by emjun** [comment] 2020-05-17 06:02
Python:1 Human: 0

The bug seems to be related to initializing ``__ALL_TESTS__`` as an empty list (``[]``). I fixed the bug by 1) setting ``__ALL_TESTS__`` to ``None`` until its first usage and 2) resetting all global solver variables at the start of the ``synthesize_tests`` function. 

This does not seem to be a very elegant solution, so I will think about potential better refactors for the longer term. 

Fixed in [this commit.](https://github.com/emjun/tea-lang/commit/680c4c2ed082468f390e7a507991b0cac203a045)

**Closed as completed** 2020-05-17 06:03 UTC
Labels: bug :bug:
